# frozen_string_literal: true

module BlockTimer
  class Printer

    type printer_opts = {
        date_formatter: ^(Date) -> String,
        decimal_formatter: ^(Float) -> String,
      }

    @logger: Logger
    @transformer: Transformer
    @opts: printer_opts
    @decimal_formatter: Proc
    @date_formatter: Proc

    def initialize: (
      ?logger: Logger,
      ?transformer: Transformer,
      ?opts: printer_opts
      ) -> self

    def call: (
        ?name: String,
        ?times: Hash[Symbol, Time]
      ) -> void

  end
end
