# frozen_string_literal: true

module BlockTimer
  class Recorder

    attr_reader times: Hash[Symbol, Time]

    def start: -> void

    def lap: (?identifier: (Symbol | nil)) -> void

    def stop: -> void

    def validate_running: () -> void
  end
end
